name:                owl
version:             0.1
github:              "heades/owl"
license:             BSD3
author:              "Harley Eades III"
maintainer:          "harley.eades@gmail.com"
copyright:           "2022 Harley Eades III"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            A functional programming language for mobile development.
# category:            Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/heades/owl#readme>

dependencies:
- base      >= 4.7 && < 5
- array     >= 0.5 && < 0.6
- mtl       >= 2.2 && < 2.3
- haskeline >= 0.8 && < 0.9
- QuickCheck >= 2.14 && < 2.15
- hspec-core >= 2.8  && < 2.9
- Diff       >= 0.4  && < 0.5
- pretty     >= 1.1  && < 1.2
library:
  source-dirs: src

executables:
  owl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:    
    - owl

tests:
  owl-test:
    main:                Spec.hs
    source-dirs:         src/test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - Diff
    - hspec-discover
    - QuickCheck
    - owl
